CREATE TABLE public.subscription (
    subscription_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier text NOT NULL,
    active bool NOT NULL,
    date_purchased timestamp with time zone NOT NULL,
    date_expires timestamp with time zone NOT NULL,
    card_name text NOT NULL,
    card_last4 text NOT NULL,
    amount_paid numeric(10, 2) NOT NULL
);

