kind: Kustomization
namespace: skad

resources:
  - ns.yaml
  - postgres.yaml
  - vulnfeed.yaml
  - subscription.yaml
  - ingress.yaml

configMapGenerator:
  - name: subscription-config
    files:
      - appsettings.prod.json=settings/appsettings.subscription.json

  - name: vulnfeed-config
    files:
      - appsettings.prod.json=settings/appsettings.vulnfeed.json

secretGenerator:
  - name: pgpassword
    files:
      - secrets/pgpassword.txt
    options:
      disableNameSuffixHash: true
  - name: pgpassfile
    files:
      - secrets/pgpassfile
    options:
      disableNameSuffixHash: true
  - name: ingress-tls
    files:
      - tls.crt=secrets/localhost.pem
      - tls.key=secrets/localhost-key.pem
    type: "kubernetes.io/tls"
    