apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: skad
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: skad-postgres:latest
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD_FILE
            value: "/run/secrets/postgres-passwd/pgpassword.txt" 
          imagePullPolicy: "Never" # Change this if needed.
          volumeMounts:
            - name: pgpassword
              mountPath: "/run/secrets/postgres-passwd"
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgpassword
          secret:
            secretName: pgpassword
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: skad
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
