apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: subscription
  namespace: skad
  labels:
    app: subscription
spec:
  selector:
    matchLabels:
      app: subscription
  serviceName: "subscription"
  replicas: 1
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: skad-subscription:latest
          ports:
            - containerPort: 80
          imagePullPolicy: "Never" # Change this if needed.
          env:
            - name: PGPASSFILE
              value: "/run/secrets/postgres/pgpassfile"
          volumeMounts:
            - name: config
              mountPath: "/opt/skad/app/k8s/"
              readOnly: true
            - name: pgpassfile
              mountPath: "/run/secrets/postgres"
              readOnly: true
            - mountPath: /opt/skad/data
              name: data
      volumes:
        - name: config
          configMap:
            name: subscription-config
        - name: pgpassfile
          secret:
            secretName: pgpassfile
        - name: data
          persistentVolumeClaim:
            claimName: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: subscription
  namespace: skad
  labels:
    app: subscription
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
      
  selector:
    app: subscription
