apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  namespace: skad
  labels:
    app: subscription
spec:
  selector:
    matchLabels:
      app: subscription
  replicas: 1
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: skad-subscription:latest
          ports:
            - containerPort: 80
          imagePullPolicy: "Never" # Change this if needed.
          env:
            - name: PGPASSFILE
              value: "/run/secrets/postgres/pgpassfile"
          volumeMounts:
            - name: config
              mountPath: "/opt/skad/app/k8s/"
              readOnly: true
            - name: pgpassfile
              mountPath: "/run/secrets/postgres"
              readOnly: true
          startupProbe:
            httpGet:
              path: /api/health/liveness
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health/liveness
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health/readiness
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: subscription-config
        - name: pgpassfile
          secret:
            secretName: pgpassfile
---
apiVersion: v1
kind: Service
metadata:
  name: subscription
  namespace: skad
  labels:
    app: subscription
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
      
  selector:
    app: subscription
